name: recycle_plus_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Fonts
  google_fonts: ^6.1.0

  # State management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # Splash screen
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0

  # Toast
  fluttertoast: ^8.2.4

  # Google map
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  location: ^5.0.3
  geolocator: ^10.1.0
  flutter_polyline_points: ^2.0.0
  custom_info_window: ^1.0.1
  url_launcher: ^6.2.1

  # Web API Request
  http: ^1.1.0
  json_serializable: ^6.7.1
  json_annotation: ^4.8.1

  # Firebase
  firebase_core: ^2.22.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  firebase_storage: ^11.4.1
  provider: ^6.1.1
  firebase_ui_auth: ^1.10.0
  uuid: ^4.2.1
  google_sign_in: ^6.1.6

  # Service locator
  get_it: ^7.6.4

  # Image
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # Localization
  intl: ^0.18.1

  # Animation
  lottie: ^2.7.0

  # Slidable List
  flutter_slidable: ^3.0.1

  # Camera
  camera: ^0.10.5+5
  permission_handler: ^11.0.1

  # Chatbot
  kommunicate_flutter: ^1.7.9

  # Image
  image: ^4.1.3
  path_provider: ^2.1.1

  # Sliding Up Panel
  sliding_up_panel: ^2.0.0+1

  # Charts
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/logo/app_logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/animations/

  fonts:
    - family: Hind Vadodara
      fonts:
        - asset: assets/fonts/HindVadodara-Regular.ttf
