const List<String> recyclingTips = [
  'Recycle right, recycle smart!',
  'Reuse before you refuse.',
  'Compost your kitchen waste.',
  'Reduce your carbon footprint: walk or bike!',
  'Save water, save the planet.',
  'Donate items instead of discarding them.',
  'Turn off lights when not in use.',
  'Shop with reusable bags.',
  'Plant a tree, grow a better future.',
  'Unplug chargers when not charging.',
  'Choose products with minimal packaging.',
  'Conserve water in every drop.',
  'Upcycle old items into something new.',
  'Recycling is a team effort!',
  'Repair instead of replacing.',
  'Say no to single-use plastics!',
  'Think before you toss.',
  'Use a refillable water bottle.',
];
